### ISSUE TITLE
yarn start doesn't work in MUI folder

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-icons#148]
#### Describe the bug

Wanted to test my icons. yarn start doesn't work. It appears that someone copy pasted scripts that contains storybook stuff in it.

```
Creating new folder in node_modules...Done
Copying build output into node_modules...cp: ./demos/storybook/node_modules/@pxblue/icons-mui: No such file or directory
cp: ./dist/.: unable to copy extended attributes to ./demos/storybook/node_modules/@pxblue/icons-mui: No such file or directory
cp: ./demos/storybook/node_modules/@pxblue/icons-mui/Priority.d.ts: No such file or directory
cp: ./demos/storybook/node_modules/@pxblue/icons-mui/Switchgear.d.ts: No such file or directory
cp: ./demos/storybook/node_modules/@pxblue/icons-mui/FaceId.js: No such file or directory
cp: ./demos/storybook/node_modules/@pxblue/icons-mui/Hops.d.ts: No such file or directory
cp: ./demos/storybook/node_modules/@pxblue/icons-mui/Soybean.js: No such file or directory
cp: ./demos/storybook/node_modules/@pxblue/icons-mui/SensorDeviceAlt.js: No such file or directory
```

#### What is the expected behavior?

Should:
1. ~Work~
2. ~Be able to run yarn start from the root folder (right now it only allows me to do it from the mui folder)~
3. Have developer instructions to document all these.

#### What are the steps to reproduce?
1. `cd mui/`
2. `yarn start`

#### Environment
MacOS Big Sur

**Comment by huayunh** [comment]
Joe fixed the build. 

Leaving this open because there is no documentation to it and the way it is executed is still confusing. Ideally, one run of `yarn start` from the root folder shall handle everything (build svg, build png, build mui components, run local host)/

**Comment by emclaug2** [comment]
Not sure if this fix works on windows; this is what I see after running `yarn && yarn start` from the root folder. 

![image](https://user-images.githubusercontent.com/6538289/141819934-d87f2a3e-9f02-47a3-abe6-9daf31714998.png)

**Comment by bkarambe** [comment]
For mac- Only the documentation is pending here.

**Comment by joebochill** [comment]
Is this still an issue with the new demo project?
