### ISSUE TITLE
Update mui-icon-builder folder with latest code

### ISSUE THREAD

**Issue by ektasawant** [etn-ccis/blui-icons#190]
#### Describe the desired behavior
Update mui-icon-builder folder with latest code (https://github.com/mui/material-ui/tree/master/packages/mui-icons-material)
#### Describe the current behavior
Currently  mui-icon-builder folder is not as per https://github.com/mui/material-ui/tree/master/packages/mui-icons-material
#### Additional Context
No

**Comment by jeffvg** [comment]
The MUI folder structure and icon names have changed due to misspelled icon names and updates for MUIv5. Rebase when we are ready.

**Comment by joebochill** [comment]
We no longer use the MUI icon builder, we use SVGR directly
