### ISSUE TITLE
Console warning in mui demo

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-icons#248]
#### Describe the bug

Things still run and visually looks good, but red stuff makes me nervous

#### What are the steps to reproduce?
1. yarn start
2. See these console warnings

#### Screenshots / Screen recording
![image](https://user-images.githubusercontent.com/8997218/205951318-80218cc0-a0bd-42f4-949e-84a3d9a96567.png)

#### Anything else to add?

I am going to guess this has to do with our themes, but I am not sure

**Comment by jeffvg** [comment]
check to see if this still exists after the new icon demo workspace refactor

**Comment by ektaghag-eaton** [comment]
No console error in current dev branch
<img width="1790" alt="Screenshot 2024-07-08 at 9 57 08 AM" src="https://github.com/etn-ccis/blui-icons/assets/133877691/5e14a385-f71c-44bc-b8fa-bc04c1e71d53">
