### ISSUE TITLE
Unable to run React demo

### ISSUE THREAD

**Issue by huayunh** [etn-ccis/blui-icons#308]
#### Describe the bug / expected behavior

The screen is blank. The console displays the error message `Uncaught Error: useNavigate() may be used only in the context of a <Router> component.`

This happens on dev branch

#### What are the steps to reproduce?

1. Git clone
2. from project root, run: `yarn install && yarn build && yarn start`

#### Screenshots / Screen recording

![image](https://github.com/etn-ccis/blui-icons/assets/8997218/c8b5749a-9f5b-4443-b219-3195a2225f79)

#### Your environment information

- node v20.11.0
- yarn v3.3.0
- macOS 14.2.1 (23C71)
- chrome 121.0.6167.184

**Comment by surajeaton** [comment]
This is probably because there are different versions of react-router and react-router-dom

**Comment by joebochill** [comment]
Yeah, there are multiple version of react-router installed:
![image](https://github.com/etn-ccis/blui-icons/assets/29152776/f90b371d-7bc7-4348-a254-3e47ab986798)

react-dom and react-router-dom need to be in sync. 
<img width="238" alt="image" src="https://github.com/etn-ccis/blui-icons/assets/29152776/4e7f047f-8cb3-48b7-bdb2-f72a40da7ca2">

This stems from this dependabot PR:
https://github.com/etn-ccis/blui-icons/pull/294/files

Updating both to `^6.22.0` (latest) in the demo resolves the issue.

**Comment by huayunh** [comment]
@joebochill Doing that will replace the old error message with new error messages on my side in my branch:
![image](https://github.com/etn-ccis/blui-icons/assets/8997218/b3b7597a-1fa0-42c9-8937-e50d660dd22c)

**Comment by joebochill** [comment]
That's a separate issue due to the changes in your branch. Updating/syncing the versions gets the demo to run on dev branch.
